import path from 'node:path';
import fs from 'node:fs/promises';

/**
 * Filesystem layout and path safety.
 *
 * DATA_DIR is /data in Docker and ./data in local dev.
 *
 *   <DATA_DIR>/songs.json          index
 *   <DATA_DIR>/songs/<id>/         one folder per project
 *   <DATA_DIR>/tmp/                upload staging + export scratch
 */

export const DATA_DIR = path.resolve(process.env.DATA_DIR ?? path.join(process.cwd(), 'data'));
export const SONGS_DIR = path.join(DATA_DIR, 'songs');
export const TMP_DIR = path.join(DATA_DIR, 'tmp');
export const INDEX_FILE = path.join(DATA_DIR, 'songs.json');

/**
 * Song ids are generated by us, but they arrive back from the client in URLs, so
 * they are untrusted input by the time we use them to build a path. This is the one
 * place a filesystem-backed app is genuinely exposed: an id of "../../etc" would
 * escape DATA_DIR entirely. Validate the shape, then verify the resolved path is
 * still inside SONGS_DIR — belt and braces, because the regex is easy to loosen
 * later without noticing what it was protecting.
 */
const ID_RE = /^[A-Za-z0-9_-]{6,32}$/;

export function isValidSongId(id: string): boolean {
  return typeof id === 'string' && ID_RE.test(id);
}

export function songDir(id: string): string {
  if (!isValidSongId(id)) throw new Error(`Invalid song id: ${JSON.stringify(id)}`);
  const dir = path.join(SONGS_DIR, id);
  const resolved = path.resolve(dir);
  if (resolved !== path.join(SONGS_DIR, id) || !resolved.startsWith(SONGS_DIR + path.sep)) {
    throw new Error('Resolved song path escaped the songs directory');
  }
  return resolved;
}

/** Resolve a file inside a song folder, rejecting any name that tries to traverse. */
export function songFile(id: string, filename: string): string {
  const dir = songDir(id);
  const base = path.basename(filename);
  if (base !== filename || base === '.' || base === '..') {
    throw new Error(`Invalid filename: ${JSON.stringify(filename)}`);
  }
  return path.join(dir, base);
}

export function projectFile(id: string): string {
  return path.join(songDir(id), 'project.json');
}

export async function ensureDataDirs(): Promise<void> {
  await fs.mkdir(SONGS_DIR, { recursive: true });
  await fs.mkdir(TMP_DIR, { recursive: true });
}

export async function pathExists(target: string): Promise<boolean> {
  try {
    await fs.access(target);
    return true;
  } catch {
    return false;
  }
}

/**
 * Sanitize a string for use as a filename or zip folder name.
 * Clone Hero itself is tolerant, but Windows is not: <>:"/\|?* are illegal, and
 * trailing dots or spaces silently break folder creation.
 */
export function sanitizeFilename(input: string, fallback = 'Untitled'): string {
  // Illegal on Windows: < > : " / \ | ? * and any control character. Spaces and
  // hyphens are deliberately kept — the export folder is named "Artist - Title".
  const ILLEGAL = new Set(['<', '>', ':', '"', '/', '\\', '|', '?', '*']);
  const cleaned = Array.from(input)
    .filter((ch) => !ILLEGAL.has(ch) && ch.codePointAt(0)! >= 0x20)
    .join('')
    .replace(/\s+/g, ' ')
    .trim()
    // Windows silently mangles names ending in a dot or space.
    .replace(/[. ]+$/, '');
  return cleaned.length > 0 ? cleaned.slice(0, 120) : fallback;
}
